services:
  - type: web
    name: scenario-comparison-web
    env: python
    plan: free
    pythonVersion: 3.12
    buildCommand: apt-get update && apt-get install -y build-essential && python -m pip install --upgrade pip setuptools wheel && python -m pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 